# Generated by Django 6.0 on 2026-01-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(max_length=5)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('supports_mpesa', models.BooleanField(default=False)),
                ('supports_airtel_money', models.BooleanField(default=False)),
                ('supports_card', models.BooleanField(default=True)),
                ('supports_bank_transfer', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('tax_name', models.CharField(default='VAT', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('phone_code', models.CharField(default='+254', max_length=5)),
                ('phone_length', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'deevents_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryConfiguration',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.country')),
                ('max_tickets_per_user', models.IntegerField(default=10)),
                ('max_resale_percentage', models.IntegerField(default=120)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('min_platform_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('min_payout_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('payout_processing_days', models.IntegerField(default=3)),
                ('requires_kyc_for_organizers', models.BooleanField(default=True)),
                ('requires_kyc_for_attendees', models.BooleanField(default=False)),
                ('kyc_document_types', models.JSONField(default=list)),
                ('date_format', models.CharField(default='dd/mm/yyyy', max_length=20)),
                ('time_format', models.CharField(default='12h', max_length=10)),
            ],
            options={
                'db_table': 'deevents_country_configurations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.ForeignKey(default='KE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.country')),
            ],
        ),
    ]
