# Generated by Django 6.0 on 2026-01-06 08:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycverification',
            options={'verbose_name': 'KYC verification', 'verbose_name_plural': 'KYC verifications'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='Kenyan National ID number', max_length=20, null=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='user',
            name='mpesa_number',
            field=models.CharField(blank=True, help_text='M-Pesa number for payments and payouts', max_length=13, null=True, verbose_name='M-Pesa number'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_field',
            field=models.CharField(default='Africa/Nairobi', max_length=50, verbose_name='timezone'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/documents/', verbose_name='document back'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_front',
            field=models.ImageField(upload_to='kyc/documents/', verbose_name='document front'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('alien_id', 'Alien ID'), ('driver_license', "Driver's License")], default='national_id', max_length=20, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie_with_document',
            field=models.ImageField(upload_to='kyc/selfies/', verbose_name='selfie with document'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submitted at'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verified at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='KE', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='KES', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='organizer status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='login count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0712345678' or '+254712345678'.", regex='^(\\+254|0)[0-9]{9}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['document_number'], name='deevents_ky_documen_ff2f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='deevents_us_is_veri_c16514_idx'),
        ),
    ]
