# Generated by Django 6.0 on 2026-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_kycverification_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kycverification',
            name='deevents_ky_user_id_f00963_idx',
        ),
        migrations.RemoveIndex(
            model_name='kycverification',
            name='deevents_ky_status_6bf56d_idx',
        ),
        migrations.RemoveIndex(
            model_name='kycverification',
            name='deevents_ky_documen_ff2f5b_idx',
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_front',
            field=models.ImageField(upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('alien_id', 'Alien ID'), ('driver_license', "Driver's License")], default='national_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie_with_document',
            field=models.ImageField(upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
