# Generated by Django 4.2.26 on 2026-01-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_kycverification_deevents_ky_user_id_f00963_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL),
        ),
    ]
