# Generated by Django 4.2.26 on 2026-01-14 07:33

from django.db import migrations
from django.utils import timezone


def fix_naive_last_login(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.filter(last_login__isnull=False):
        if timezone.is_naive(user.last_login):
            user.last_login = timezone.make_aware(user.last_login)
            user.save(update_fields=['last_login'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kycverification_verified_by'),
    ]

    operations = [
        migrations.RunPython(fix_naive_last_login),
    ]
