# Generated by Django 4.2.26 on 2026-01-14 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique_for_date=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users_30d', models.PositiveIntegerField(default=0)),
                ('total_organizers', models.PositiveIntegerField(default=0)),
                ('total_organizations', models.PositiveIntegerField(default=0)),
                ('pending_kyc', models.PositiveIntegerField(default=0)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('active_events', models.PositiveIntegerField(default=0)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue_kes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revenue_crypto', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('pending_payouts', models.PositiveIntegerField(default=0)),
                ('pending_disputes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Statistic',
                'verbose_name_plural': 'Platform Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
