# Generated by Django 4.2.26 on 2026-01-14 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformstat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
